### ISSUE TITLE
p text renderer btw

### ISSUE THREAD

**Issue by TerikKek** [Gopro336/CLEAN_Phobos_1.9.0-BUILDABLE-SRC#1]
https://ill-down-your.net/OKybPVWm
not a problem with ur orignal jar btw

**Comment by TerikKek** [comment]
https://ill-down-your.net/bz5i7hQ1 also the fucking rainbow suffix no workie

**Comment by Gopro336** [comment]
ok il take a look

**Comment by Gopro336** [comment]
does this happen with my 1.7.2 src?

**Comment by TerikKek** [comment]
i think it does

**Comment by TerikKek** [comment]
also the nametags got raped in this version of the jar that i built from the src

**Comment by Gopro336** [comment]
for the text rendering, I think its a problem related to Unicode after being decompiled. For the chat it could also be a mixin issue. Il fix it when I find time most likely this weekend.

**Comment by TerikKek** [comment]
most of these problems arent prevalent in the prebuilt jar

**Comment by Gopro336** [comment]
so the jar in releases doesent have this problem? or are you talking about my clean jar that is not from this src

**Comment by Hqrion** [comment]
dude stop complaining about a fucking decompiled jar lmfao

**Comment by TerikKek** [comment]
the jar in releases does not have this problem. the rainbow text issue is still prevalent in both versions.

**Comment by 1440-2b2t** [comment]
> dude stop complaining about a fucking decompiled jar lmfao

Lmfao hes trying to help get the src to perfection

**Comment by Hqrion** [comment]
decompiled src to perfection pffftttt

**Comment by aaa826** [comment]
The original jar didn't have this problem weird

**Comment by TerikKek** [comment]
the one he built did not have the problem

**Comment by Hqrion** [comment]
complaining about leaked client troll

**Comment by Gopro336** [comment]
Im sorry, but I will not be spending any more time on this source as I have better things to do with my time.
