### ISSUE TITLE
big

### ISSUE THREAD

**Issue by oyzipfile** [Gopro336/CLEAN_Phobos_1.9.0-BUILDABLE-SRC#6]
When I join into singleplay and server.. Lol
> at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> 	at net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd(EntityLivingBase.java) ~[EntityLivingBase.class:?]
> [21:27:34] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\mycom\Desktop\Dev\Siagaurity\run\.\crash-reports\crash-2021-02-23_21.27.34-server.txt
> [21:27:34] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
> [21:27:34] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
> [21:27:34] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Player269 lost connection: Server closed
> [21:27:34] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Player269 left the game
> [21:27:34] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Stopping singleplayer server as player logged out
> [21:27:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
> [21:27:35] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: java.lang.NullPointerException
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java:418)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.renderer.EntityRenderer.handler$getMouseOverHook$zzp000(EntityRenderer.java:2287)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1294)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1115)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1208)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.client.main.Main.main(Main.java:118)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
> [21:27:40] [main/INFO] [STDERR]: [net.minecraft.client.renderer.EntityRenderer:handler$getMouseOverHook$zzp000:2290]: 	at GradleStart.main(GradleStart.java:25)
> [21:27:41] [Server thread/INFO] [FML]: Unloading dimension 0
> [21:27:41] [Server thread/INFO] [FML]: Applying holder lookups
> [21:27:41] [Server thread/INFO] [FML]: Holder lookups applied
> [21:27:41] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
> [21:27:45] [main/INFO] [STDOUT]: [net.minecraft.client.Minecraft:unload:3602]: Shutting down: saving configuration
> [21:27:45] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] <Phobos.eu> IRC is not connected!
> [21:27:47] [main/INFO] [STDOUT]: [net.minecraft.client.Minecraft:unload:3604]: Configuration saved.
> [21:27:47] [main/INFO] [STDOUT]: [net.minecraft.client.Minecraft:unload:3602]: Shutting down: saving configuration

**Comment by Gopro336** [comment]
Im sorry, but I will not be spending any more time on this source.
